# Generated by Django 4.0 on 2021-12-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jewelry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10000)),
                ('code', models.CharField(max_length=10000)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('description', models.CharField(default='Joya de plata 925.', max_length=10000)),
                ('sold', models.BooleanField()),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
