# Generated by Django 4.0 on 2021-12-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
