# Generated by Django 4.0 on 2021-12-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_jewelry_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
