# Generated by Django 4.0 on 2021-12-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_jewelry_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='price',
            field=models.CharField(max_length=10000),
        ),
    ]
