# Generated by Django 4.0 on 2021-12-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_jewelry_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jewel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10000)),
                ('code', models.CharField(max_length=10000)),
                ('quantity', models.IntegerField()),
                ('price', models.CharField(max_length=10000)),
                ('description', models.CharField(default='Joya de plata 925.', max_length=10000)),
                ('size', models.IntegerField(null=True)),
                ('sold', models.BooleanField(default=False)),
                ('picture', models.FileField(null=True, upload_to='static/media')),
            ],
        ),
        migrations.DeleteModel(
            name='Jewelry',
        ),
    ]
