# Generated by Django 4.0 on 2021-12-17 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_jewel_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jewel',
            new_name='Jewelry',
        ),
    ]
