# Generated by Django 4.0 on 2021-12-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_jewel_jewelry'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelry',
            name='price_int',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
